name: Build Lutz Term

on:
  workflow_dispatch:
  push:
    branches:
      - lutzterm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Lutz Term
        uses: actions/checkout@v4
        with:
          path: app

      - name: Checkout Lutz Term packages
        uses: actions/checkout@v4
        with:
          repository: padukalutz/LutzTerm-packages
          ref: lutzterm
          path: packages

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build bootstrap
        working-directory: packages
        run: |
          chmod +x scripts/build-bootstraps.sh
          ./scripts/run-docker.sh \
            ./scripts/build-bootstraps.sh \
            --architectures aarch64

      - name: Install bootstrap
        working-directory: app
        run: |
          mkdir -p app/src/main/cpp

          find ../packages \
            -type f \
            -name 'bootstrap-*.zip' \
            -exec cp {} app/src/main/cpp/ \;

          echo "Bootstrap files:"
          ls -lh app/src/main/cpp/

      - name: Build APK
        working-directory: app
        env:
          TERMUX_PACKAGE_VARIANT: apt-android-7
          TERMUX_APP_VERSION_NAME: 0.118.0-lutz
          TERMUX_APK_VERSION_TAG: lutzterm-${{ github.run_number }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Lutz-Term-APK
          path: app/app/build/outputs/apk/debug/*.apk
